baseURL = "https://hxloise.github.io/labveilletech"
languageCode = "fr-CH"
theme = "hugo-winston-theme"
themesDir = "themes"
title = "Héloïse Cuche"
paginate = 3
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  google_analytics_id = ""
  # twitter_handle = "@zerostaticio"
  showAuthorOnHomepage = false
  showAuthorOnPosts = false
  showPostsOnHomepage = false
  addDot = true
  addFrame = false
  highlightColor = '#ffffff'
  baseColor = "#000000"
  baseOffsetColor = "#eaeaea"
  headingColor = "#95A0BF"
  textColor = "#95A0BF"
  dotColor = "#95A0BF"

# markdown config settings https://gohugo.io/getting-started/configuration-markup/#goldmark
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = 1
